### ISSUE TITLE
No example of plotting without jupyter

### ISSUE THREAD

**Issue by ags-dy** [has2k1/plotnine#274]
Apologies if I missed this, but I was not able to find an example that uses a plain matplotlib window.  My attempts at getting to work have failed.  What am I doing wrong?

```
import pandas as pd
import numpy as np
from plotnine import *
import matplotlib.pyplot as plt

n = 10
df = pd.DataFrame({'x': np.arange(n),
                   'y': np.arange(n),
                   'yfit': np.arange(n) + np.tile([-.2, .2], n // 2),
                   'cat': ['a', 'b'] * (n // 2)})

a = (ggplot(df)
     + geom_col(aes('x', 'y'))
     )

#this works
a.save("test.pdf")

fig, ax = plt.subplots()
#this does not
a._draw_using_figure(fig, ax)


/usr/bin/python2.7 /home/ags/python_modules/workspaceAnalysis/TestLibs/testplotnine.py
/usr/local/lib/python2.7/dist-packages/plotnine/ggplot.py:708: UserWarning: Saving 6 x 4 in image.
  from_inches(height, units), units))
/usr/local/lib/python2.7/dist-packages/plotnine/ggplot.py:709: UserWarning: Filename: test.pdf
  warn('Filename: {}'.format(filename))
/usr/local/lib/python2.7/dist-packages/plotnine/positions/position_stack.py:99: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data['ymin'] = np.min([heights[:-1], heights[1:]], axis=0)
/usr/local/lib/python2.7/dist-packages/plotnine/positions/position_stack.py:100: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data['ymax'] = np.max([heights[:-1], heights[1:]], axis=0)
/usr/local/lib/python2.7/dist-packages/plotnine/positions/position_stack.py:104: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data['y'] = ((1-vjust)*data['ymin'] + vjust*data['ymax'])
Traceback (most recent call last):
  File "/home/ags/python_modules/workspaceAnalysis/TestLibs/testplotnine.py", line 20, in <module>
    a._draw_using_figure(fig, ax)
  File "/usr/local/lib/python2.7/dist-packages/plotnine/ggplot.py", line 263, in _draw_using_figure
    raise err
TypeError: 'AxesSubplot' object does not support indexing

```

Thanks

**Comment by has2k1** [comment]
Jupyter automatically prints the last object in the cell (it also outputs any Matplotlib figures that are created in the cell), unless if that object is `None` then nothing is printed.
That is how -- as if by magic -- the plot shows up when using Jupyter. Just print the ggplot object. For your case

```python
import pandas as pd
import numpy as np
from plotnine import *

n = 10
df = pd.DataFrame({'x': np.arange(n),
                   'y': np.arange(n),
                   'yfit': np.arange(n) + np.tile([-.2, .2], n // 2),
                   'cat': ['a', 'b'] * (n // 2)})

a = (ggplot(df)
     + geom_col(aes('x', 'y'))
     )
print(a)
```

**Comment by ags-dy** [comment]
Thanks,

The print works, but I would like to be able to use: 

```
fig, ax = plt.subplots(1,2)
some other matplotlib plot not supported by plot9(ax[0])
a._draw_using_figure(fig, ax[1])
```

because I have another 3d subplot next to the plotnine one.  Is it possible to draw without using print?

**Comment by has2k1** [comment]
Have you tried `plt.show()`?

**Comment by has2k1** [comment]
> heh, good point. No I have not (and should add that to the example) but it crashes on ...

I was not following closely. Obviously you are bound to encounter monsters when you reach in for the internal functions. You are on your own, but here is a life line *maybe*!

```python
fig, ax = plt.subplots()
fig._themeable = {}
a._draw_using_figure(fig, [ax])
```

**Comment by ags-dy** [comment]
thanks,  that works now.

It still comes up with the warnings probably due to my abuse of the internal functions.  Is there a plan to allow this type of mixing with non plotnine graphs?

**Comment by has2k1** [comment]
> Is there a plan to allow this type of mixing with non plotnine graphs?

No there isn't any more than is currently possible. The best way to go about it is let plotnine
manage the creation of the figure and axes. Then plot on them afterwards.


```python
import pandas as pd
import numpy as np
from plotnine import *

n = 10
df = pd.DataFrame({'x': np.arange(n),
                   'y': np.arange(n),
                   'yfit': np.arange(n) + np.tile([-.2, .2], n // 2),
                   'cat': ['a', 'b'] * (n // 2)})

a = (ggplot(df)
     + geom_col(aes('x', 'y'))
     )

fig = a.draw()
fig.axes  # You can plot more stuff on the axes using Matplotlib !!!
```

**Comment by ags-dy** [comment]
Ok, great.  Thanks for the tip!
