### ISSUE TITLE
colorbrewer_all_schemes.json missing when creating executable with PyInstaller

### ISSUE THREAD

**Issue by psandev** [has2k1/plotnine#419]
Hi,
I am not sure if I have to bring this issue here since it is related to Pyinstaller, but it seems that there is a missing file, which is not a part of plotline, which is missing and prevents the executable to run. 

I found an issue opened at PyInstaller GitHub, but there was no solution posted and I haven't been able to fix it.
https://github.com/pyinstaller/pyinstaller/issues/3923

Here is the console output when I try to run the executable:

C:\Users\xxx\Dropbox\Landa\Python Projects\Monitoring_Analysis\dist>wave_check.exe "C:\Landa\Logs\Monitoring\QCS - after fix smoothing kernel checkbox checked with smoothing\Front"
c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:623: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "wave_check.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\qplot.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\ggplot.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\facets\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\facets\facet_grid.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\facets\facet.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\scales\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\plotnine\scales\scale_alpha.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\mizani\palettes.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\palettable\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\palettable\colorbrewer\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\palettable\colorbrewer\colorbrewer.py", line 14, in <module>
  File "site-packages\pkg_resources\__init__.py", line 1156, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1401, in get_resource_string
  File "site-packages\pkg_resources\__init__.py", line 1570, in _get
  File "c:\virtualenv\python36_pyqtgraph\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 471, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\_MEI356402\\palettable\\colorbrewer\\data\\colorbrewer_all_schemes.json'
[13872] Failed to execute script wave_check

Pyinstaller - 3.6
plotnine - 0.7
Matplotlib - 3.13

**Comment by has2k1** [comment]
This seem to be relatted to [palettable](https://github.com/jiffyclub/palettable), which is a dependency. I think the problem is the installer only (or by default) includes packages (directories with a __init__.py file) and https://github.com/jiffyclub/palettable/tree/master/palettable/colorbrewer/data is not a package so it is ignored.

**Comment by psandev** [comment]
Thank you. That is what I suspected, but I am still unable to include the file in the build. I will look for assistance with Pyinstaller guys. Thanks again.
