### ISSUE TITLE
plotnine import fails with latest matplotlib

### ISSUE THREAD

**Issue by paolap** [has2k1/plotnine#620]
Hi after updating to the latest matplotlib the package fails to import as it can't import
matplotlib._contour

matplotlib version is 3.6.0

it worked fine with 3.5.3

>>> import plotnine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/ggplot.py", line 18, in <module>
    from .facets import facet_null
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/facets/__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/facets/facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/facets/facet.py", line 14, in <module>
    from ..scales.scales import Scales
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/scales/__init__.py", line 83, in <module>
    from .limits import xlim, ylim, lims, expand_limits
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/scales/limits.py", line 8, in <module>
    from ..geoms import geom_blank
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/geoms/__init__.py", line 6, in <module>
    from .geom_abline import geom_abline
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/geoms/geom_abline.py", line 9, in <module>
    from .geom import geom
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/geoms/geom.py", line 3, in <module>
    from ..stats.stat import stat
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/stats/__init__.py", line 7, in <module>
    from .stat_density_2d import stat_density_2d
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.07/lib/python3.9/site-packages/plotnine/stats/stat_density_2d.py", line 3, in <module>
    import matplotlib._contour as _contour
ModuleNotFoundError: No module named 'matplotlib._contour'

**Comment by CarlosVecina** [comment]
Same here.

Although it is duplicated: 
#619 
And already fixed:
https://github.com/has2k1/plotnine/commit/ #c48d5a26ab0d0a54ed47bbefc6a83b5fcb2af616

It was due to a internal _matplotlib_ call that is no longer supported and [has been replaced](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#improved-quad-contour-calculations-via-contourpy:~:text=%2C%20png)-,Improved%20quad%20contour%20calculations%20via%20ContourPy,-%23)

So @paolap, I guess you could choose to downgrade to 3.5.3 or to install plotnine@main till the next plotnine release.

**Comment by paolap** [comment]
Thanks, I must have missed that issue
