### ISSUE TITLE
Error on import when using Python 3

### ISSUE THREAD

**Issue by dansbecker** [has2k1/plotnine#71]
I installed plotnine in Python 3 using the command `pip install plotnine`.  

Running `python -c "from plotnine import ggplot"` yields the error 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/__init__.py", line 3, in <module>
    from .qplot import qplot            # noqa: F401
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/qplot.py", line 11, in <module>
    from .ggplot import ggplot
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/ggplot.py", line 17, in <module>
    from .facets import facet_null
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/facets/__init__.py", line 3, in <module>
    from .facet_grid import facet_grid
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/facets/facet_grid.py", line 10, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/facets/facet.py", line 13, in <module>
    from ..scales.scales import Scales
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/scales/__init__.py", line 4, in <module>
    from .scale_alpha import scale_alpha
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/scales/scale_alpha.py", line 9, in <module>
    from .scale import scale_discrete, scale_continuous, scale_datetime
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/plotnine/scales/scale.py", line 18, in <module>
    from mizani.transforms import gettrans
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/mizani/transforms.py", line 431, in <module>
    _doc='Logit Transformation')
  File "/Users/dan/anaconda/envs/py35/lib/python3.5/site-packages/mizani/transforms.py", line 407, in probability_trans
    raise ValueError(msg.format(distribution))
ValueError: Unknown distribution 'logistic'
```

It installs and loads fine from a Python 2 environment.

**Comment by has2k1** [comment]
What version of scipy do have installed?

**Comment by dansbecker** [comment]
I had 0.18.1 installed.  

Upgrading to 1.0.0 resolved the error.

I'm sending over a PR to add the version requirements in `setup.py` though I'm not 100% sure that's the right place (sorry if it isn't and the PR is just clutter for you to close).  Thanks for the help.

**Comment by has2k1** [comment]
As far as I can tell, scipy 0.18.1 is not the problem. It may have been a case of mixed up packages.

This works for me:

```bash
# In a new virtual environment
$ pip install scipy==0.18.1
$ pip install plotnine
$ python -c "from plotnine import ggplot"
```

Even checking the scipy code, the [logistic](https://github.com/scipy/scipy/blob/v0.18.1/scipy/stats/_continuous_distns.py#L3046) function is present in v0.18.1 and in much older versions.

I did not set a minimum version of scipy because it has not always been easy to install on all platforms. v1.0.0 may have changed that but I am not sure if that will always be the case.

**Comment by dansbecker** [comment]
Ok. I'm sort of lost then.  If you want to follow up on this, I'm happy to do what I can to reproduce it.  It sounds like it's something strange in my environment, that isn't worth following up on.  In which case, I'm grateful for the help that got me to fix this.

**Comment by has2k1** [comment]
It is not necessary to chase down the root cause, unless you run into it again. Leave the PR open, I'll look more into the availability of v1.0.0.
